/*
 * This file is generated by jOOQ.
 */
package ru.template.telegram.bot.kotlin.template.domain;


import ru.template.telegram.bot.kotlin.template.domain.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
