/*
 * This file is generated by jOOQ.
 */
package ru.template.telegram.bot.kotlin.template.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Nonnull;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long   id;
    private String stepCode;
    private String text;
    private String accept;

    public Users() {}

    public Users(Users value) {
        this.id = value.id;
        this.stepCode = value.stepCode;
        this.text = value.text;
        this.accept = value.accept;
    }

    public Users(
        @Nonnull Long   id,
        String stepCode,
        String text,
        String accept
    ) {
        this.id = id;
        this.stepCode = stepCode;
        this.text = text;
        this.accept = accept;
    }

    /**
     * Getter for <code>public.users.id</code>.
     */
    @Nonnull
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.users.id</code>.
     */
    public void setId(@Nonnull Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.users.step_code</code>.
     */
    public String getStepCode() {
        return this.stepCode;
    }

    /**
     * Setter for <code>public.users.step_code</code>.
     */
    public void setStepCode(String stepCode) {
        this.stepCode = stepCode;
    }

    /**
     * Getter for <code>public.users.text</code>.
     */
    public String getText() {
        return this.text;
    }

    /**
     * Setter for <code>public.users.text</code>.
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * Getter for <code>public.users.accept</code>.
     */
    public String getAccept() {
        return this.accept;
    }

    /**
     * Setter for <code>public.users.accept</code>.
     */
    public void setAccept(String accept) {
        this.accept = accept;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Users other = (Users) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (stepCode == null) {
            if (other.stepCode != null)
                return false;
        }
        else if (!stepCode.equals(other.stepCode))
            return false;
        if (text == null) {
            if (other.text != null)
                return false;
        }
        else if (!text.equals(other.text))
            return false;
        if (accept == null) {
            if (other.accept != null)
                return false;
        }
        else if (!accept.equals(other.accept))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.stepCode == null) ? 0 : this.stepCode.hashCode());
        result = prime * result + ((this.text == null) ? 0 : this.text.hashCode());
        result = prime * result + ((this.accept == null) ? 0 : this.accept.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(stepCode);
        sb.append(", ").append(text);
        sb.append(", ").append(accept);

        sb.append(")");
        return sb.toString();
    }
}
